export const RULES_TEXT = [
  "中文：",
  "台籍預排特休規則",
  "1. 請依照表格上公告的日期範圍輸入。",
  "2. 第一次申請請輸入工號和日期，例如：A1234 6/3。若表格日期很清楚，也可輸入：A1234 3。",
  "3. 第一次完成後，之後可以只輸入日期，例如：6/4 或 4。",
  "4. 同一個日期最多開放 3 名人員申請特休，額滿請改選其他日期。",
  "5. 已申請後如需變更，請聯絡組長。",
  "6. 查詢日期狀況請輸入：查詢 6/3 或 查詢 3。",
  "",
  "English:",
  "Taiwan staff special leave pre-registration rules",
  "1. Please enter a date within the date range shown in the sheet.",
  "2. For the first request, enter your worker ID and date, for example: A1234 6/3. If the sheet date is clear, you may also enter: A1234 3.",
  "3. After the first request, you can enter only the date, for example: 6/4 or 4.",
  "4. Each date allows up to 3 people to request special leave. If full, please choose another date.",
  "5. If you need to change a registered date, please contact the leader.",
  "6. To check a date, enter: status 6/3 or status 3.",
  "",
  "Tiếng Việt:",
  "Quy định đăng ký trước nghỉ phép đặc biệt cho nhân viên Đài Loan",
  "1. Vui lòng nhập ngày nằm trong phạm vi ngày được thông báo trên bảng.",
  "2. Lần đầu đăng ký, vui lòng nhập mã nhân viên và ngày, ví dụ: A1234 6/3. Nếu ngày trên bảng rõ ràng, cũng có thể nhập: A1234 3.",
  "3. Sau lần đăng ký đầu tiên, lần sau chỉ cần nhập ngày, ví dụ: 6/4 hoặc 4.",
  "4. Mỗi ngày tối đa 3 người được đăng ký nghỉ phép đặc biệt. Nếu đã đủ, vui lòng chọn ngày khác.",
  "5. Nếu cần đổi ngày đã đăng ký, vui lòng liên hệ tổ trưởng.",
  "6. Để kiểm tra một ngày, nhập: kiem tra 6/3 hoặc kiem tra 3.",
].join("\n");
